# Generated by Django 3.1.2 on 2020-12-02 13:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='年齢')),
                ('sex', models.CharField(choices=[['male', '男性'], ['female', '女性']], max_length=10, verbose_name='性別')),
                ('address', models.CharField(choices=[['0', '北海道'], ['1', '青森'], ['2', '秋田'], ['3', '岩手'], ['4', '山形'], ['5', '宮城'], ['6', '新潟'], ['7', '福島'], ['8', '栃木'], ['9', '茨城'], ['10', '石川県'], ['11', '富山県'], ['12', '群馬'], ['13', '埼玉'], ['14', '千葉'], ['15', '長野'], ['16', '山梨'], ['17', '東京'], ['18', '神奈川'], ['19', '福井'], ['20', '岐阜'], ['21', '静岡'], ['22', '京都'], ['23', '滋賀'], ['24', '愛知'], ['25', '三重'], ['26', '鳥取'], ['27', '兵庫'], ['28', '大阪'], ['29', '奈良'], ['30', '島根'], ['31', '岡山'], ['32', '和歌山'], ['33', '広島'], ['34', '香川'], ['35', '徳島'], ['36', '山口'], ['37', '愛媛'], ['38', '高知'], ['39', '福岡'], ['40', '大分'], ['41', '佐賀'], ['42', '熊本'], ['43', '宮崎'], ['44', '長崎'], ['45', '鹿児島'], ['46', '沖縄']], max_length=10, verbose_name='都道府県')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('profileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keijiban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toukou', models.TextField(verbose_name='投稿内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('good', models.IntegerField(blank=True, null=True)),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
