# Generated by Django 3.1.2 on 2020-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20201204_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/'),
        ),
    ]
