# Generated by Django 3.1.2 on 2020-12-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20201204_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[['男性', '男性'], ['女性', '女性']], max_length=10, verbose_name='性別'),
        ),
    ]
