# Generated by Django 3.1.2 on 2020-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_auto_20201206_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keijiban',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
